### ISSUE TITLE
Support for accruals (periodisation) for cash book entries

### ISSUE THREAD

**Issue by prognostikos** [substancelab/rconomic#71]
I want to add support for accruals/periodisation on cash book entries.

From what I can see, there are two options for supporting this, and I'd love to get some feedback on what would be the preferred way to add it.

One option would be to add support for accruals to `CashBookEntryProxy#create_cash_book_entry_for_handles` so that it's supported at creation time. It looks like we'd need to support an optional handle for the capitalisation account.

Another option would be to add direct support for updating the cash book entries using [CashBookEntry_SetAccrualInformation](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=CashBookEntry_SetAccrualInformation), as has been done with `CashBookEntryProxy#set_due_date`.

Any preferences as to which way to go? Or is there another option I haven't considered above?

**Comment by koppen** [comment]
The one-to-one mapping of the API we get by wrapping `CashBookEntry_SetAccrualInformation` directly is nice and probably the least surprising way. Perhaps also the easiest addition?

That said it would mean an extra (or more) HTTP requests since it could only be done after actually creating the `CashBookEntry`. Is it possible to avoid this if we hook into `create_cash_book_entry_for_handles`?

Is there a SOAP operation that allows us to set the capitalisation info for a CashBookEntry on creation-time, though? As far as I can tell, none of the `CreateFinanceVoucher`, `CreateDebtorPayment`, `CreateCreditorInvoice`, `CreateCreditorPayment`, nor `CreateManualDebtorInvoice` operations lets us do it in a single operation anyways.

I think I am leaning towards just implementing `CashBookEntry_SetAccrualInformation` seeing how it maps directly to the SOAP API and probably is the smallest possible change. Although, I will happily admit that I have no clue how accruals work or what the simplest use case is, so I am likely missing something.

**Comment by prognostikos** [comment]
I actually figured out that I could set the accrual information directly on the entries and save them, so this isn't necessary after all.
